import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Fotter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Blockmetric</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <h1>Main Page</h1>
      <Footer />
    </div>
  );
}
